### ISSUE TITLE
请问这个和Halo自带的编辑器粘贴图片自动上传图床有什么区别吗

### ISSUE THREAD

**Issue by Star1128** [johnhom1024/picgo-plugin-halo#1]
👀

**Comment by baozishu** [comment]
富文本可以直接上传
MD编辑器不能
如果说 PicGO 配合 Typora 编辑一篇 直接复制粘贴就好

**Comment by johnhom1024** [comment]
@baozishu 说的对，这是用来解决Halo官方自带的另一个MD编辑器（byteMD）无法上传附件的另一种方法。
