### ISSUE TITLE
插件安装不上

### ISSUE THREAD

**Issue by baozishu** [johnhom1024/picgo-plugin-halo#2]
![M{ZLI {RS_675)IA}A4A0@G](https://user-images.githubusercontent.com/60163088/224492840-6c5fc299-8ad8-4f55-884b-1c948fc81a97.png)

**Comment by johnhom1024** [comment]
我这边删掉了重新下载，好像没有遇到你的这个问题。你可以看下能不能通过npm安装这个插件

**Comment by baozishu** [comment]
npm安装 
也是安装不上 同样的 我用的 picGo 1.4 测试版 有影响吗

**Comment by johnhom1024** [comment]
npm有报错信息嘛？可以贴一下npm的报错信息

**Comment by johnhom1024** [comment]
可以尝试多下载几次，可能会因为网络的原因导致下载失败
